force-app/main/default/objects/Aluno__c/Aluno__c.object-meta.xml
<CustomObject>
    <description>Dados do aluno.</description>
    <label>Aluno</label>
    <nameField>
        <label>Nome de Aluno</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Alunos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Aluno__c/fields/Ativo__c.field-meta.xml
<CustomField>
    <fullName>Ativo__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Status do aluno.</description>
    <label>Ativo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Aluno__c/fields/Classe__c.field-meta.xml
<CustomField>
    <fullName>Classe__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Classe que o aluno esta estudando.</description>
    <label>Classe</label>
    <referenceTo>Classe__c</referenceTo>
    <relationshipLabel>Alunos</relationshipLabel>
    <relationshipName>Alunos</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Aluno__c/fields/CPF__c.field-meta.xml
<CustomField>
    <fullName>CPF__c</fullName>
    <description>CPF do aluno.</description>
    <externalId>true</externalId>
    <inlineHelpText>Entre com o CPF do aluno.</inlineHelpText>
    <label>CPF</label>
    <length>14</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Aluno__c/fields/Data_de_Nascimento__c.field-meta.xml
<CustomField>
    <fullName>Data_de_Nascimento__c</fullName>
    <description>Data de nascimento do aluno.</description>
    <inlineHelpText>Entre com a data de nascimento do aluno.</inlineHelpText>
    <label>Data de Nascimento</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Aluno__c/fields/Escola__c.field-meta.xml
<CustomField>
    <fullName>Escola__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Escola</description>
    <label>Escola</label>
    <referenceTo>Escola__c</referenceTo>
    <relationshipLabel>Alunos</relationshipLabel>
    <relationshipName>Alunos</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Aluno__c/fields/Sobrenome__c.field-meta.xml
<CustomField>
    <fullName>Sobrenome__c</fullName>
    <description>Sobrenome do aluno.</description>
    <inlineHelpText>Entre com o sobrenome do aluno.</inlineHelpText>
    <label>Sobrenome</label>
    <length>155</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Classe__c/Classe__c.object-meta.xml
<CustomObject>
    <description>Classes de aula.</description>
    <label>Classe</label>
    <nameField>
        <label>Nome de Classe</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Classe__c/fields/Escola__c.field-meta.xml
<CustomField>
    <fullName>Escola__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Escola da classe</description>
    <label>Escola</label>
    <referenceTo>Escola__c</referenceTo>
    <relationshipLabel>Classes</relationshipLabel>
    <relationshipName>Classes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Classe__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Escolher uma opção</description>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Criado</fullName>
            </value>
            <value>
                <fullName>Em curso</fullName>
            </value>
            <value>
                <fullName>Formada</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Escola__c/Escola__c.object-meta.xml
<CustomObject>
    <description>Dados da escola.</description>
    <label>Escola</label>
    <nameField>
        <label>Nome de Escola</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Escolas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Escola__c/fields/Cidade__c.field-meta.xml
<CustomField>
    <fullName>Cidade__c</fullName>
    <description>Cidade onde reside a escola.</description>
    <inlineHelpText>Entre com a Cidade.</inlineHelpText>
    <label>Cidade</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Escola__c/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <description>CNPJ da escola</description>
    <externalId>true</externalId>
    <inlineHelpText>Digite o CNPJ da escola</inlineHelpText>
    <label>CNPJ</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Escola__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <description>Estado onde reside a escola.</description>
    <inlineHelpText>Escolha um estado.</inlineHelpText>
    <label>Estado</label>
    <length>155</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Escola__c/fields/Pais__c.field-meta.xml
<CustomField>
    <fullName>Pais__c</fullName>
    <description>País onde reside a escola.</description>
    <inlineHelpText>Escolha o País.</inlineHelpText>
    <label>País</label>
    <length>155</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TesteHelper.cls
@IsTest
 public class TesteHelper {

//     public static Aluno__c criarAluno(Id classe, Id escola) {

//             Aluno__c aluno = new Aluno__c();
//             aluno.Name = ('Aluno');
//             aluno.Ativo__c = true;
//             aluno.Classe__c = classe;
//             aluno.CPF__C = gerarCPF();
//             aluno.Data_de_Nascimento__c = Date.newInstance(2020, 01, 03);
//             aluno.Escola__c = escola;
//             aluno.Sobrenome__c = 'Sobrenome';
//             return aluno;
//     }

//     public static Classe__c criarClasse(Id escola) {
         
//         Classe__c classe = new Classe__c();
//         classe.Name = 'Classe';
//         classe.Escola__c = escola;
//         classe.Status__c = 'Criado';
//         return classe;

//     } 

//     public static Escola__c criarEscola() {
         
//         Escola__c escola = new Escola__c();
//         escola.Name = ('Escola');
//         escola.Cidade__c = ('Cidade');
//         escola.CNPJ__C = gerarCNPJ();
//         escola.Estado__c = ('SP');
//         escola.Pais__c = ('Brasil');
//         return escola; 
//     }
   
//     private static String gerarCNPJ() {
//         Integer digito1 = 0; 
//         Integer digito2 = 0;
//         Integer resto = 0;
//         String nDigResult;
//         String numerosContatenados;
//         String numeroGerado;

//         //numeros gerados
//         Integer n1 = Integer.valueof((Math.random() * 10));
//         Integer n2 = Integer.valueof((Math.random() * 10));
//         Integer n3 = Integer.valueof((Math.random() * 10));
//         Integer n4 = Integer.valueof((Math.random() * 10));
//         Integer n5 = Integer.valueof((Math.random() * 10));
//         Integer n6 = Integer.valueof((Math.random() * 10));
//         Integer n7 = Integer.valueof((Math.random() * 10));
//         Integer n8 = Integer.valueof((Math.random() * 10));
//         Integer n9 = Integer.valueof((Math.random() * 10));
//         Integer n10 = Integer.valueof((Math.random() * 10)); 
//         Integer n11 = Integer.valueof((Math.random() * 10)); 
//         Integer n12 = Integer.valueof((Math.random() * 10)); 

//         Integer soma = n12*2 + n11*3 + n10*4 + n9*5 + n8*6 + n7*7 + n6*8 + n5*9 + n4*2 + n3*3 + n2*4 + n1*5;

//         Integer valor = (soma / 11) * 11;

//         digito1 = soma - valor;

//         //Primeiro resto da divisão por 11.
//         resto = Math.mod(digito1, 11);

//         if(digito1 < 2){
//             digito1 = 0;
//         }
//         else {
//             digito1 = 11 - resto;
//         }

//         Integer soma2 =  digito1*2 + n12*3 + n11*4 + n10*5 + n9*6 + n8*7 + n7*8 + n6*9 + n5*2 + n4*3 + n3*4 + n2*5 + n1*6 ;

//         Integer valor2 = (soma2 / 11)*11;

//         digito2 = soma2-valor2;

//         //Primeiro resto da divisão por 11.
//         resto = Math.mod(digito2, 11);

//         if(digito2 < 2){
//             digito2 = 0;
//         }
//         else {
//             digito2 = 11-resto;
//         }

//         //Conctenando os numeros
//         numerosContatenados = String.valueOf(n1) + String.valueOf(n2) + '.' + String.valueOf(n3) + String.valueOf(n4) +
//                             String.valueOf(n5) + '.' + String.valueOf(n6) + String.valueOf(n7) +String.valueOf(n8) + '/' +
//                             String.valueOf(n9) + String.valueOf(n10) + String.valueOf(n11) +
//                             String.valueOf(n12) + '-';

//         //Concatenando o primeiro resto com o segundo.
//         nDigResult = String.valueOf(digito1) + String.valueOf(digito2);

//         numeroGerado = numerosContatenados+nDigResult;

//         return numeroGerado;
//     }

//     private static String gerarCPF() {
//         Integer digito1 = 0; 
//         Integer digito2 = 0; 
//         Integer resto = 0;
//         String  nDigResult;
//         String numerosContatenados;
//         String numeroGerado;

//         //numeros gerados
//         Integer n1 = Integer.valueof((Math.random() * 10));
//         Integer n2 = Integer.valueof((Math.random() * 10));
//         Integer n3 = Integer.valueof((Math.random() * 10));
//         Integer n4 = Integer.valueof((Math.random() * 10));
//         Integer n5 = Integer.valueof((Math.random() * 10));
//         Integer n6 = Integer.valueof((Math.random() * 10));
//         Integer n7 = Integer.valueof((Math.random() * 10));
//         Integer n8 = Integer.valueof((Math.random() * 10));
//         Integer n9 = Integer.valueof((Math.random() * 10));

//         Integer soma = n9*2 + n8*3 + n7*4 + n6*5 + n5*6 + n4*7 + n3*8 + n2*9 + n1*10;

//         Integer valor = (soma / 11)*11;

//         digito1 = soma-valor;

//         //Primeiro resto da divisão por 11.
//         resto = Math.mod(digito1, 11);

//         if(digito1 < 2) {
//             digito1 = 0;
//         }
//         else {
//             digito1 = 11 - resto;
//         }

//         Integer soma2 = digito1 * 2 + n9*3 + n8*4 + n7*5 + n6*6 + n5*7 + n4*8 + n3*9 + n2*10 + n1*11;

//         Integer valor2 = (soma2 / 11)*11;

//         digito2 = soma2 - valor2;

//         //Primeiro resto da divisão por 11.
//         resto = Math.mod(digito2, 11);

//         if(digito2 < 2) {
//             digito2 = 0;
//         }
//         else {
//             digito2 = 11-resto;
//         }

//         //Conctenando os numeros
//         numerosContatenados = String.valueOf(n1) + String.valueOf(n2) + String.valueOf(n3) + '.' + String.valueOf(n4) +
//                             String.valueOf(n5) + String.valueOf(n6) + '.' + String.valueOf(n7) + String.valueOf(n8)  +
//                             String.valueOf(n9) + '-';

//         //Concatenando o primeiro resto com o segundo.
//         nDigResult = String.valueOf(digito1) + String.valueOf(digito2);

//         numeroGerado = numerosContatenados + nDigResult;

//         return numeroGerado;
//     }

 }