force-app/main/default/objects/Aluno__c/Aluno__c.object-meta.xml
<CustomObject>
    <description>Dados do aluno.</description>
    <label>Aluno</label>
    <nameField>
        <label>Nome de Aluno</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Alunos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Aluno__c/fields/Classe__c.field-meta.xml
<CustomField>
    <fullName>Classe__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Classe que o aluno esta estudando.</description>
    <label>Classe</label>
    <referenceTo>Classe__c</referenceTo>
    <relationshipLabel>Alunos</relationshipLabel>
    <relationshipName>Alunos</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Aluno__c/fields/Escola__c.field-meta.xml
<CustomField>
    <fullName>Escola__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Escola</description>
    <label>Escola</label>
    <referenceTo>Escola__c</referenceTo>
    <relationshipLabel>Alunos</relationshipLabel>
    <relationshipName>Alunos</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Classe__c/Classe__c.object-meta.xml
<CustomObject>
    <description>Classes de aula.</description>
    <label>Classe</label>
    <nameField>
        <label>Nome de Classe</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Classe__c/fields/Escola__c.field-meta.xml
<CustomField>
    <fullName>Escola__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Escola da classe</description>
    <label>Escola</label>
    <referenceTo>Escola__c</referenceTo>
    <relationshipLabel>Classes</relationshipLabel>
    <relationshipName>Classes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Classe__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Escolher uma opção</description>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Criado</fullName>
            </value>
            <value>
                <fullName>Em curso</fullName>
            </value>
            <value>
                <fullName>Formada</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Escola__c/Escola__c.object-meta.xml
<CustomObject>
    <description>Dados da escola.</description>
    <label>Escola</label>
    <nameField>
        <label>Nome de Escola</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Escolas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/Classe_Teste.cls
@IsTest
public class Classe_Teste {
    @IsTest
    public static void validarClasses(){

        List<Escola__c> escolas =  new List<Escola__c>();
        List<Classe__c> classes =  new List<Classe__c>();
        List<Aluno__c> alunos = new List<Aluno__c>();
        
        Integer quantidade = 10;

        Test.startTest();

        for(Integer i = 0; i < quantidade; i++){
            escolas.Add(TesteHelper.criarEscola());  
        }
        insert escolas;

        for(Escola__c escola : escolas){
            classes.Add(TesteHelper.criarClasse(escola.Id));
        }
        insert classes;

        for(Classe__c classe : classes){
            alunos.Add(TesteHelper.criarAluno(classe.Id, classe.Escola__c)); 
        } 
        for(Classe__c classeDif : classes){
            classeDif.Status__c = 'Em curso';
        }
        
        update classes;
        insert alunos;
        Test.stopTest();
    }
}