force-app/main/default/objects/Escola__c/Escola__c.object-meta.xml
<CustomObject>
    <description>Dados da escola.</description>
    <label>Escola</label>
    <nameField>
        <label>Nome de Escola</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Escolas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Escola__c/fields/Cidade__c.field-meta.xml
<CustomField>
    <fullName>Cidade__c</fullName>
    <description>Cidade onde reside a escola.</description>
    <inlineHelpText>Entre com a Cidade.</inlineHelpText>
    <label>Cidade</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Escola__c/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <description>CNPJ da escola</description>
    <externalId>true</externalId>
    <inlineHelpText>Digite o CNPJ da escola</inlineHelpText>
    <label>CNPJ</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Escola__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <description>Estado onde reside a escola.</description>
    <inlineHelpText>Escolha um estado.</inlineHelpText>
    <label>Estado</label>
    <length>155</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Escola__c/fields/Pais__c.field-meta.xml
<CustomField>
    <fullName>Pais__c</fullName>
    <description>País onde reside a escola.</description>
    <inlineHelpText>Escolha o País.</inlineHelpText>
    <label>País</label>
    <length>155</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Escola__c/fields/RazaoSocial__c.field-meta.xml
<CustomField>
    <fullName>RazaoSocial__c</fullName>
    <label>Razao Social</label>
    <length>155</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/UtilHelper.cls
public class UtilHelper {
    
    public class ReceitaWSData {
        public String nome;
        public String uf;
        public String municipio;
        public String fantasia;
    }

    @future(callout=true)
    public static void servicoAtualizarNomePorCNPJ(String escolaId) {

        List<Escola__c> escolas = [SELECT Id, CNPJ__c FROM Escola__c WHERE Id = :escolaId];

        if(!escolas.isEmpty()) {
            String jsonData = '';

            Escola__c escola = escolas[0];

            try {
                String cnpj = escola.CNPJ__c.replace('.', '').replace('/', '').replace('-', '');

                HttpRequest requisicao = new HttpRequest();
                requisicao.setTimeout(5000);
                requisicao.setMethod('GET');
                requisicao.setEndpoint(String.format('https://www.receitaws.com.br/v1/cnpj/{0}', new String[] { cnpj }));

                Http caller = new Http();
                HttpResponse resposta = caller.send(requisicao);

                jsonData = resposta.getBody();

                ReceitaWSData dados = (ReceitaWSData)JSON.deserialize(jsonData, ReceitaWSData.class);

                escola.RazaoSocial__c = dados.nome;
                escola.Cidade__c = dados.municipio;
                escola.Estado__c = dados.uf;
                escola.Pais__c = 'BRASIL';
                escola.Name = dados.fantasia != '' ? dados.fantasia : dados.nome;

                TriggerHandler.bypass('EscolaTriggerHandler');
                update escolas;
                TriggerHandler.clearByPass('EscolaTriggerHandler');
            }
            catch(Exception ex) {
                System.debug(ex);
                System.debug('JSON: ' + jsonData);
            }
        }
    }
}