force-app/main/default/objects/Escola__c/Escola__c.object-meta.xml
<CustomObject>
    <description>Dados da escola.</description>
    <label>Escola</label>
    <nameField>
        <label>Nome de Escola</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Escolas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Escola__c/fields/RazaoSocial__c.field-meta.xml
<CustomField>
    <fullName>RazaoSocial__c</fullName>
    <label>Razao Social</label>
    <length>155</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/EscolaTriggerHandler.cls
public class EscolaTriggerHandler extends TriggerHandler {

    public override void afterUpdate() {
        List<Escola__c> escolas = Trigger.new;
        
        for(Escola__c escola : escolas){
            UtilHelper.servicoAtualizarNomePorCNPJ(escola.Id);
            System.debug('Escola razão social = ' + escola.RazaoSocial__c);
        }
        //comentario de indicação e teste
        //novo comentario 01
    }    
}